- name: Playbook to push image to docker hub
  hosts: dev_*
  become: true
  gather_facts: false
  tasks:
    - name: creating docker image
      command: docker build -t myproject .
      args:
        chdir: /tmp/docker
    - name: log in to Docker Hub
      docker_login:
        username: timojeaga
        password: Jayden123&    
    - name: adding tag to image
      command: docker tag myproject timojeaga/myproject
    - name: push image to dockerhub
      command: docker push timojeaga/myproject


     

        
 

       
