- hosts: dev_*
  gather_facts: no
  become_user: root
  tasks:
  - name: packages | ensure apt list dir exists
    file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755
  - name: install docker sdk
    apt:
      name: python3-pip, docker.io
      update_cache: yes
      state: present
      cache_valid_time: 3600
  - name: install python3-docker
    pip:
      name: docker
      state: present
  - name: create file
    file:
      path: /tmp/docker
      state: directory
  - name: install Apache HTTP Server
    apt:
      name: apache2
      state: present
  - name: start apache2 service
    service: name=apache2 state=started
  - name: Deploy the html code
    copy: src: "~/home/jenkins/workspace/myansible/index.hml 
      src=index.html dest=/var/www/html
  - name: Restart apache2 server
    service: name=apache2 state=restarted
  - name: copy files
    copy:
      src: "~/home/jenkins/workspace/myansible/{{ item }}"
      dest: /tmp/docker
      owner: ubuntu
    with_items:
      - Dockerfile
      - index.html
  - name: Buile image
    docker_image:
      name: timojeaga
      tag: v1.0
      source: build
      build:
        path: /tmp/docker





  
    
    
    
