- hosts: dev_*
  gather_facts: no
  become_user: root
  tasks:
  - name: packages | ensure apt list dir exists
    file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755
  - name: install docker sdk
    apt:
      name: python3-pip, docker.io
      update_cache: yes
      state: present
      cache_valid_time: 3600
  - name: install python3-docker
    pip:
      name: docker
      state: present
  - name: create file
    file:
      path: /tmp/docker
      state: directory
  - name: install Apache HTTP Server
    apt:
      name: apache2
      state: present
  - name: start apache2 service
    service: name=apache2 state=started
  - name: Deploy the html code
    copy: src=index.html dest=/var/www/html
  - name: Restart apache2 server
    service: name=apache2 state=restarted
  - name: Update the System Packages
    apt:
      upgrade: yes
      update_cache: yes
 
  - name: Create a Tomcat User
    user:
      name: tomcat
 
  - name: Create a Tomcat Group
    group:
      name: tomcat
 
  - name: Install JAVA
    apt:
      name: default-jdk
      state: present
 
  - name: Create a Tomcat Directory
    file:
      path: /opt/tomcat10
      owner: tomcat
      group: tomcat
      mode: 755
      recurse: yes
 
  - name: download & unarchive tomcat10 
    unarchive:
      src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz
      dest: /opt/tomcat10
      remote_src: yes
      extra_opts: [--strip-components=1]
 
  - name: Change ownership of tomcat directory
    file:
      path: /opt/tomcat10
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: Start and Enable Tomcat 10 on sever
    systemd:
      name: tomcat
      state: started
      daemon_reload: true    
    
  - name: copy index.html
    copy:
      src: "/home/jenkins/workspace/myansible/{{item}}"
      dest: /tmp/docker
      owner: root
    with_items:
      - index.html
      - Dockerfile
      - target
      - src
      - pom.xml
      - addressbook_screenshot.png 
      - build.properties 
      - build.xml 
  - name: Buile image
    docker_image:
      name: timojeaga
      tag: v1.0
      source: build
      build:
        path: /tmp/docker
  - name: creating docker image
    command: docker build -t myproject .
    args:
      chdir: /tmp/docker
  - name: log in to Docker Hub
    docker_login:
      username: timojeaga
      password: Jayden123&    
  - name: adding tag to image
    command: docker tag myproject timojeaga/myproject
  - name: push image to dockerhub
    command: docker push timojeaga/myproject
