- hosts: dev_*
  gather_facts: no
  become_user: root
  tasks:
  - name: packages | ensure apt list dir exists
    file:
      path: /var/lib/apt/lists/
      state: directory
      mode: 0755
  - name: install docker sdk
    apt:
      name: python3-pip, docker.io
      update_cache: yes
      state: present
      cache_valid_time: 3600
  - name: install python3-docker
    pip:
      name: docker
      state: present
  - name: create file
    file:
      path: /tmp/docker
      state: directory
  - name: install Apache HTTP Server
    apt:
      name: apache2
      state: present
  - name: start apache2 service
    service: name=apache2 state=started
  - name: Deploy the html code
    copy: src=index.html dest=/var/www/html
  - name: Restart apache2 server
    service: name=apache2 state=restarted
  - name: copy index.html
    copy:
      src: "/home/jenkins/workspace/myansible/index.html"
      dest: /tmp/doc
      owner: root
    with_items:
      - index.html
  - name: copy dockerfile
    copy:
      src: "/home/jenkins/workspace/myansible/Dockerfile"
      dest: /tmp/doc
      owner: root
    with_items:
      - Dockerfile
  - name: Buile image
    docker_image:
      name: timojeaga
      tag: v1.0
      source: build
      build:
        path: /tmp/docker
  - name: creating docker image
    command: docker build -t myproject .
    args:
      chdir: /tmp/docker
  - name: log in to Docker Hub
    docker_login:
      username: timojeaga
      password: Jayden123&    
  - name: adding tag to image
    command: docker tag myproject timojeaga/myproject
  - name: push image to dockerhub
    command: docker push timojeaga/myproject


     

        
 

       
